import { useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, Linking, Platform, Share, Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS } from '@constants/index';
import { useReportStore } from '@stores/index';
import { scheduleMoveAlerts, configureNotifications } from '@services/notificationService';
import type { FishingReport, SpeciesSection, ScheduleEntry, RigRecommendation, TrollRoute, BaitSearchArea } from '@app-types/index';

const MONO = Platform.select({ ios: 'Menlo', android: 'monospace', web: 'monospace', default: 'monospace' });

/** Build a GPX file from all GPS spots, anchor pins, bait search, and troll routes */
function buildGpxFile(report: FishingReport): string {
  // Fishing spot waypoints
  const spotWaypoints = report.species.flatMap((sp) =>
    sp.spots.flatMap((spot) => {
      const desc = [
        `Species: ${sp.speciesName}`,
        `Bite: ${sp.biteWindow}`,
        spot.depthFt ? `Depth: ${spot.depthFt}` : '',
        `Rig: ${sp.rig.name}`,
        spot.notes,
      ].filter(Boolean).join(' | ');
      const wpts = [`  <wpt lat="${spot.coordinates.lat}" lon="${spot.coordinates.lng}">
    <name>${escapeXml(spot.name)}</name>
    <desc>${escapeXml(desc)}</desc>
    <sym>Fishing Area</sym>
    <type>Fishing</type>
  </wpt>`];
      // Anchor pin waypoints
      if (spot.anchorPinEbb) {
        wpts.push(`  <wpt lat="${spot.anchorPinEbb.lat}" lon="${spot.anchorPinEbb.lng}">
    <name>ANCHOR-EBB-${escapeXml(spot.name)}</name>
    <desc>${escapeXml(spot.anchorPinEbb.notes ?? 'Ebb tide anchor drop')}</desc>
    <sym>Anchor</sym>
    <type>Anchor</type>
  </wpt>`);
      }
      if (spot.anchorPinFlood) {
        wpts.push(`  <wpt lat="${spot.anchorPinFlood.lat}" lon="${spot.anchorPinFlood.lng}">
    <name>ANCHOR-FLOOD-${escapeXml(spot.name)}</name>
    <desc>${escapeXml(spot.anchorPinFlood.notes ?? 'Flood tide anchor drop')}</desc>
    <sym>Anchor</sym>
    <type>Anchor</type>
  </wpt>`);
      }
      return wpts;
    })
  );

  // Bait search waypoint
  const baitWpt = report.baitSearchArea ? [`  <wpt lat="${report.baitSearchArea.coordinates.lat}" lon="${report.baitSearchArea.coordinates.lng}">
    <name>${escapeXml(report.baitSearchArea.name)}</name>
    <desc>${escapeXml([report.baitSearchArea.method, report.baitSearchArea.species].filter(Boolean).join(' — '))}</desc>
    <sym>Bait</sym>
    <type>Bait</type>
  </wpt>`] : [];

  // Troll routes
  const routes = (report.trollRoutes ?? []).map((route) => {
    const rtepts = route.waypoints.map((wp) =>
      `    <rtept lat="${wp.lat}" lon="${wp.lng}"></rtept>`
    ).join('\n');
    return `  <rte>
    <name>${escapeXml(route.name)}</name>
    <desc>${escapeXml([route.speed ? `Speed: ${route.speed}` : '', route.notes].filter(Boolean).join(' — '))}</desc>
${rtepts}
  </rte>`;
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="NGN Fishing — ngnfishing.com"
  xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>NGN Fishing Report — ${report.input?.date ?? 'Unknown'}</name>
    <desc>Generated by NGN Fishing (No Guide Needed)</desc>
    <time>${report.generatedAt}</time>
  </metadata>
${[...spotWaypoints, ...baitWpt].join('\n')}
${routes.join('\n')}
</gpx>`;
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function buildShareText(report: FishingReport): string {
  const lines = [
    `NGN Fishing Report — ${report.input?.date ?? ''}`,
    ``,
    `Conditions: ${report.conditionsSummary}`,
    ``,
    ...report.species.map((sp) => [
      `${sp.speciesName}`,
      `  Bite window: ${sp.biteWindow}`,
      `  Top spot: ${sp.spots[0]?.name ?? '—'}`,
      `  Rig: ${sp.rig.name}`,
    ].join('\n')),
    ``,
    `Powered by NGN Fishing — No Guide Needed`,
    `ngnfishing.com`,
  ];
  return lines.join('\n');
}

export default function ReportScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { activeReport, reports } = useReportStore();
  const [alertsScheduled, setAlertsScheduled] = useState(false);

  const report: FishingReport | undefined =
    id === 'latest'
      ? activeReport ?? reports[0]
      : reports.find((r) => r.id === id) ?? activeReport ?? undefined;

  if (!report) {
    return (
      <SafeAreaView style={s.safe}>
        <View style={s.empty}>
          <Text style={s.emptyText}>No report found.</Text>
        </View>
      </SafeAreaView>
    );
  }

  const openMaps = (lat: number, lng: number, name: string) => {
    if (Platform.OS === 'ios') {
      // Apple Maps: use ll= for exact coordinates, q= for pin label
      const url = `maps://0,0?ll=${lat},${lng}&q=${encodeURIComponent(name)}`;
      Linking.openURL(url).catch(() => {
        // Fallback to Google Maps web with exact coordinates
        Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${lat},${lng}`);
      });
    } else {
      // Android / Web: Google Maps with exact lat/lng coordinates
      const url = `https://www.google.com/maps/search/?api=1&query=${lat},${lng}`;
      Linking.openURL(url);
    }
  };

  const openAmazonSearch = (query: string) => {
    const url = `https://www.amazon.com/s?k=${encodeURIComponent(query)}&tag=ngnfishing-20`;
    Linking.openURL(url);
  };

  return (
    <SafeAreaView style={s.safe} edges={['bottom']}>
      <ScrollView contentContainerStyle={s.content}>

        {/* Header */}
        <Text style={s.genAt}>
          Generated {new Date(report.generatedAt).toLocaleString('en-US', {
            month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit',
          })}
        </Text>

        {/* Offshore Go/No-Go */}
        {report.offshoreGoNoGo && (
          <View style={[s.goNoGo, { borderColor: getGoNoGoColor(report.offshoreGoNoGo.status) }]}>
            <Text style={[s.goNoGoLabel, { color: getGoNoGoColor(report.offshoreGoNoGo.status) }]}>
              {report.offshoreGoNoGo.status === 'go'      ? 'GO'       :
               report.offshoreGoNoGo.status === 'caution' ? 'CAUTION'  : 'NO GO'}
            </Text>
            <Text style={s.goNoGoReasoning}>{report.offshoreGoNoGo.reasoning}</Text>
          </View>
        )}

        {/* Conditions Summary */}
        <View style={s.card}>
          <Text style={s.cardTitle}>Conditions</Text>
          <Text style={s.bodyText}>{report.conditionsSummary}</Text>
        </View>

        {/* Launch Plan */}
        {report.launchPlan && (
          <View style={s.card}>
            <Text style={s.cardTitle}>Launch Plan</Text>
            <Text style={s.bodyText}>{report.launchPlan}</Text>
          </View>
        )}

        {/* Payoff Window */}
        {report.payoffWindow && (
          <View style={s.payoffCard}>
            <Text style={s.payoffTitle}>Payoff Window</Text>
            <Text style={s.bodyText}>{report.payoffWindow}</Text>
          </View>
        )}

        {/* Species Sections */}
        {report.species.map((sp) => (
          <SpeciesCard key={sp.speciesId} species={sp} onNavigate={openMaps} onShopRig={openAmazonSearch} />
        ))}

        {/* Full Day Schedule */}
        {report.schedule.length > 0 && (
          <View style={s.card}>
            <Text style={s.cardTitle}>Full Day Schedule</Text>
            {report.schedule.map((entry, i) => (
              <ScheduleRow key={i} entry={entry} />
            ))}
          </View>
        )}

        {/* Bait Finder */}
        {report.baitFinderTip && (
          <View style={s.card}>
            <Text style={s.cardTitle}>Cast Net Bait Finder</Text>
            <Text style={s.bodyText}>{report.baitFinderTip}</Text>
          </View>
        )}

        {/* Coaching Notes */}
        {report.coachingNotes && report.coachingNotes.length > 0 && (
          <View style={s.card}>
            <Text style={s.cardTitle}>Captain's Notes</Text>
            {report.coachingNotes.map((note, i) => (
              <Text key={i} style={s.coachingNote}>{note}</Text>
            ))}
          </View>
        )}

        {/* Pro Tips */}
        {report.proTips.length > 0 && (
          <View style={s.card}>
            <Text style={s.cardTitle}>Pro Tips</Text>
            {report.proTips.map((tip, i) => (
              <Text key={i} style={s.proTip}>• {tip}</Text>
            ))}
          </View>
        )}

        {/* Share + Download */}
        <View style={s.actionRow}>
          <TouchableOpacity
            style={s.actionBtn}
            onPress={async () => {
              try {
                await Share.share({
                  message: buildShareText(report),
                  title: 'NGN Fishing Report',
                });
              } catch {}
            }}
            activeOpacity={0.8}
          >
            <Text style={s.actionBtnIcon}>↗</Text>
            <Text style={s.actionBtnText}>SHARE</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={s.actionBtn}
            onPress={() => {
              // On web: copy to clipboard. On native: share as text file
              if (Platform.OS === 'web') {
                if (typeof navigator !== 'undefined' && navigator.clipboard) {
                  navigator.clipboard.writeText(buildShareText(report));
                  Alert.alert('Copied', 'Report copied to clipboard.');
                }
              } else {
                Share.share({ message: buildShareText(report), title: 'NGN Fishing Report' });
              }
            }}
            activeOpacity={0.8}
          >
            <Text style={s.actionBtnIcon}>⬇</Text>
            <Text style={s.actionBtnText}>DOWNLOAD</Text>
          </TouchableOpacity>
        </View>

        {/* Send to Chartplotter — GPX Export */}
        <TouchableOpacity
          style={s.chartplotterBtn}
          onPress={() => {
            const gpx = buildGpxFile(report);
            if (Platform.OS === 'web') {
              // Trigger file download in browser
              try {
                const blob = new Blob([gpx], { type: 'application/gpx+xml' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `ngn-report-${report.input?.date ?? 'spots'}.gpx`;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
              } catch {
                // Fallback: copy to clipboard
                if (typeof navigator !== 'undefined' && navigator.clipboard) {
                  navigator.clipboard.writeText(gpx);
                  Alert.alert('GPX Copied', 'GPX data copied to clipboard. Paste into a .gpx file and load onto your chartplotter.');
                }
              }
            } else {
              // Native: share as file attachment
              Share.share({
                message: gpx,
                title: `NGN Report ${report.input?.date ?? ''}.gpx`,
              });
            }
          }}
          activeOpacity={0.8}
        >
          <Text style={s.chartplotterIcon}>📡</Text>
          <View>
            <Text style={s.chartplotterText}>SEND TO CHARTPLOTTER</Text>
            <Text style={s.chartplotterSub}>Download .GPX — Garmin · Lowrance · Humminbird · Simrad</Text>
          </View>
        </TouchableOpacity>

        {/* Print Report (web only) */}
        {Platform.OS === 'web' && (
          <TouchableOpacity
            style={s.printBtn}
            onPress={() => {
              if (typeof window !== 'undefined' && window.print) {
                window.print();
              }
            }}
            activeOpacity={0.8}
          >
            <Text style={s.printBtnIcon}>🖨</Text>
            <Text style={s.printBtnText}>PRINT MY REPORT</Text>
          </TouchableOpacity>
        )}

        {/* Goin' Fishin' CTA */}
        <TouchableOpacity
          style={s.goinFishin}
          onPress={async () => {
            // Schedule move-timing push notifications
            if (!alertsScheduled && report.schedule.length > 0) {
              try {
                await configureNotifications();
                const alerts = await scheduleMoveAlerts(report);
                if (alerts.length > 0) {
                  setAlertsScheduled(true);
                  Alert.alert(
                    'Alerts Armed 🎣',
                    `${alerts.length} move-timing alerts scheduled. You'll get notified when it's time to reposition.`,
                    [{ text: 'Tight Lines!', onPress: () => router.push('/tabs/triplog' as any) }]
                  );
                  return;
                }
              } catch {}
            }
            router.push('/tabs/triplog' as any);
          }}
          activeOpacity={0.85}
        >
          <Text style={s.goinFishinText}>
            {alertsScheduled ? 'ALERTS ARMED ✓' : "GOIN' FISHIN' 🎣"}
          </Text>
          <Text style={s.goinFishinSub}>
            {alertsScheduled
              ? 'Move alerts scheduled — tap to log your trip'
              : 'Accept this report — we\'ll alert you when to move'}
          </Text>
        </TouchableOpacity>

      </ScrollView>
    </SafeAreaView>
  );
}

function SpeciesCard({
  species,
  onNavigate,
  onShopRig,
}: {
  species: SpeciesSection;
  onNavigate: (lat: number, lng: number, name: string) => void;
  onShopRig: (query: string) => void;
}) {
  return (
    <View style={s.speciesCard}>
      <Text style={s.speciesTitle}>{species.speciesName}</Text>
      <Text style={s.biteWindow}>Bite window: {species.biteWindow}</Text>
      <Text style={s.bodyText}>{species.biteWindowReasoning}</Text>

      {/* Spots with coordinates + navigation */}
      {species.spots.length > 1 && (
        <TouchableOpacity
          style={s.routeAllBtn}
          onPress={() => {
            // Open first spot — user navigates sequentially
            const first = species.spots[0];
            if (first) onNavigate(first.coordinates.lat, first.coordinates.lng, first.name);
          }}
          activeOpacity={0.8}
        >
          <Text style={s.routeAllText}>NAVIGATE ALL {species.spots.length} SPOTS →</Text>
          <Text style={s.routeAllSub}>Opens GPS to first spot. Tap next spot when ready.</Text>
        </TouchableOpacity>
      )}
      {species.spots.map((spot, spotIdx) => (
        <TouchableOpacity
          key={spot.id}
          style={s.spotRow}
          onPress={() => onNavigate(spot.coordinates.lat, spot.coordinates.lng, spot.name)}
          activeOpacity={0.75}
        >
          <View style={s.spotInfo}>
            <View style={s.spotHeader}>
              <Text style={s.spotIndex}>{spotIdx + 1}</Text>
              <View style={{ flex: 1 }}>
                <Text style={s.spotName}>{spot.name}</Text>
                <Text style={s.spotCoords}>
                  {spot.coordinates.lat.toFixed(4)}°N, {Math.abs(spot.coordinates.lng).toFixed(4)}°W
                </Text>
              </View>
            </View>
            {spot.depthFt && <Text style={s.spotDepth}>Depth: {spot.depthFt}</Text>}
            <Text style={s.spotNotes}>{spot.notes}</Text>
            {spot.arrivalTime && (
              <Text style={s.arrivalTime}>Arrive by {spot.arrivalTime}</Text>
            )}
          </View>
          <Text style={s.navIcon}>Navigate →</Text>
        </TouchableOpacity>
      ))}

      {/* Rig + Knot + Tackle */}
      <View style={s.rigBox}>
        <Text style={s.rigSectionHeader}>RIG</Text>
        <Text style={s.rigTitle}>{species.rig.name}</Text>
        {species.rig.hookSize && <Text style={s.rigDetail}>Hook: {species.rig.hookSize}</Text>}
        {species.rig.leader   && <Text style={s.rigDetail}>Leader: {species.rig.leader}</Text>}
        {species.rig.weight   && <Text style={s.rigDetail}>Weight: {species.rig.weight}</Text>}
        <Text style={s.rigDetail}>Presentation: {species.rig.baitPresentation}</Text>

        {/* Knot */}
        {species.rig.knotName && (
          <View style={s.knotRow}>
            <Text style={s.rigSectionHeader}>KNOT</Text>
            <Text style={s.knotName}>{species.rig.knotName}</Text>
          </View>
        )}

        {/* Tackle List */}
        {species.rig.tackleList && species.rig.tackleList.length > 0 && (
          <View style={s.tackleSection}>
            <Text style={s.rigSectionHeader}>TACKLE LIST</Text>
            {species.rig.tackleList.map((item, i) => (
              <Text key={i} style={s.tackleItem}>• {item}</Text>
            ))}
          </View>
        )}

        {/* Shop This Rig */}
        <TouchableOpacity
          style={s.shopBtn}
          onPress={() => {
            const query = `${species.rig.name} fishing rig tackle`;
            onShopRig(query);
          }}
          activeOpacity={0.8}
        >
          <Text style={s.shopBtnText}>Shop This Rig →</Text>
        </TouchableOpacity>
      </View>

      {/* Bait */}
      <View style={s.baitBox}>
        <Text style={s.rigSectionHeader}>BAIT</Text>
        <Text style={s.bodyText}>{species.baitRecommendation}</Text>
      </View>

      <Text style={s.speciesProTip}>{species.proTip}</Text>

      {/* Regs */}
      <Text style={s.regsText}>
        {species.regulations.state} regs: {species.regulations.sizeLimitIn} min · Bag limit: {species.regulations.bagLimit}
      </Text>
    </View>
  );
}

function ScheduleRow({ entry }: { entry: ScheduleEntry }) {
  return (
    <View style={s.scheduleRow}>
      <Text style={s.scheduleTime}>{entry.time}</Text>
      <View style={s.scheduleInfo}>
        <Text style={s.scheduleSpecies}>{entry.species}</Text>
        <Text style={s.scheduleLocation}>{entry.location}</Text>
        <Text style={s.scheduleTide}>{entry.tide} · {entry.rig}</Text>
      </View>
    </View>
  );
}

function getGoNoGoColor(status: 'go' | 'caution' | 'no_go'): string {
  return status === 'go' ? COLORS.success : status === 'caution' ? COLORS.warning : COLORS.danger;
}

const s = StyleSheet.create({
  safe:            { flex: 1, backgroundColor: COLORS.navy },
  content:         { padding: 20, paddingBottom: 48 },
  empty:           { flex: 1, alignItems: 'center', justifyContent: 'center' },
  emptyText:       { color: COLORS.textMuted, fontSize: 16 },
  genAt:           { fontSize: 12, color: COLORS.textMuted, marginBottom: 20 },

  // Go/No-Go
  goNoGo: {
    borderWidth:   1.5,
    borderRadius:  10,
    padding:       16,
    marginBottom:  16,
  },
  goNoGoLabel:     { fontSize: 20, fontWeight: '800', marginBottom: 6 },
  goNoGoReasoning: { fontSize: 14, color: COLORS.textSecondary, lineHeight: 22 },

  // Standard card
  card: {
    backgroundColor: COLORS.navyLight,
    borderRadius:    10,
    padding:         16,
    marginBottom:    14,
  },
  cardTitle:       { fontSize: 15, fontWeight: '700', color: COLORS.white, marginBottom: 10 },
  bodyText:        { fontSize: 15, color: COLORS.textSecondary, lineHeight: 23 },

  // Payoff Window — the one card that keeps a color accent
  payoffCard: {
    backgroundColor: COLORS.navyLight,
    borderRadius:    10,
    padding:         16,
    marginBottom:    14,
    borderWidth:     1,
    borderColor:     `${COLORS.warning}40`,
  },
  payoffTitle:     { fontSize: 15, fontWeight: '700', color: COLORS.warning, marginBottom: 10 },

  // Species card — no colored top border, subtle separator
  speciesCard: {
    backgroundColor: COLORS.navyLight,
    borderRadius:    10,
    padding:         16,
    marginBottom:    14,
    borderTopWidth:  1,
    borderTopColor:  `${COLORS.white}12`,
  },
  speciesTitle:    { fontSize: 19, fontWeight: '700', color: COLORS.white, marginBottom: 4 },
  biteWindow:      { fontSize: 14, color: COLORS.seafoam, fontWeight: '600', marginBottom: 8 },

  // Navigate all spots button
  routeAllBtn: {
    backgroundColor: `${COLORS.seafoam}10`,
    borderWidth:     1,
    borderColor:     `${COLORS.seafoam}50`,
    borderRadius:    8,
    padding:         12,
    marginTop:       12,
    alignItems:      'center',
  },
  routeAllText:    { fontSize: 12, fontWeight: '700', color: COLORS.seafoam, letterSpacing: 1 },
  routeAllSub:     { fontSize: 10, color: COLORS.textMuted, marginTop: 3 },

  // Individual spot row
  spotRow: {
    flexDirection:   'row',
    alignItems:      'center',
    borderBottomWidth: 0.5,
    borderBottomColor: `${COLORS.white}10`,
    paddingVertical: 12,
    paddingHorizontal: 4,
    marginTop:       2,
  },
  spotInfo:        { flex: 1 },
  spotHeader:      { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  spotIndex: {
    fontSize: 14, fontWeight: '700', color: COLORS.seafoam,
    width: 24, textAlign: 'center', lineHeight: 24,
  },
  spotName:        { fontSize: 15, fontWeight: '600', color: COLORS.white },
  spotCoords:      { fontSize: 10, color: COLORS.textMuted, fontFamily: MONO, marginTop: 2, letterSpacing: 0.5 },
  spotDepth:       { fontSize: 13, color: COLORS.textMuted, marginTop: 4, marginLeft: 34 },
  spotNotes:       { fontSize: 13, color: COLORS.textSecondary, marginTop: 3, marginLeft: 34, lineHeight: 20 },
  arrivalTime:     { fontSize: 12, color: COLORS.seafoam, marginTop: 4, fontWeight: '600', marginLeft: 34 },
  navIcon:         { fontSize: 13, color: COLORS.seafoam, fontWeight: '600', paddingLeft: 8 },

  // Rig box
  rigBox: {
    backgroundColor: `${COLORS.navy}60`,
    borderRadius:    8,
    padding:         14,
    marginTop:       14,
  },
  rigSectionHeader: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.textMuted,
    letterSpacing: 1.5,
    marginBottom: 4,
    marginTop: 8,
  },
  rigTitle:        { fontSize: 15, fontWeight: '700', color: COLORS.white, marginBottom: 4 },
  rigDetail:       { fontSize: 13, color: COLORS.textSecondary, marginTop: 2, lineHeight: 20 },

  knotRow:         { marginTop: 4 },
  knotName:        { fontSize: 14, fontWeight: '600', color: COLORS.white },

  tackleSection:   { marginTop: 4 },
  tackleItem:      { fontSize: 13, color: COLORS.textSecondary, marginTop: 3, paddingLeft: 4, lineHeight: 20 },

  // Shop button — seafoam for interactive
  shopBtn: {
    backgroundColor: COLORS.seafoam,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginTop: 14,
  },
  shopBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.navy,
    letterSpacing: 0.5,
  },

  // Bait box — no left border
  baitBox: {
    paddingTop: 12,
    marginTop: 10,
    borderTopWidth: 0.5,
    borderTopColor: `${COLORS.white}12`,
  },

  // Pro tip inside species card
  speciesProTip:   { fontSize: 14, color: COLORS.textSecondary, marginTop: 12, lineHeight: 22, fontStyle: 'italic' },
  // Coaching notes
  coachingNote:    { fontSize: 15, color: COLORS.textSecondary, marginTop: 8, lineHeight: 23 },
  // Pro tips in standalone section
  proTip:          { fontSize: 14, color: COLORS.textSecondary, marginTop: 8, lineHeight: 22 },
  regsText:        { fontSize: 12, color: COLORS.textMuted, marginTop: 10 },

  // Schedule
  scheduleRow:     { flexDirection: 'row', paddingVertical: 12, borderTopWidth: 0.5, borderTopColor: `${COLORS.white}10` },
  scheduleTime:    { fontSize: 14, fontWeight: '700', color: COLORS.seafoam, width: 80, fontFamily: MONO },
  scheduleInfo:    { flex: 1 },
  scheduleSpecies: { fontSize: 14, fontWeight: '600', color: COLORS.white },
  scheduleLocation:{ fontSize: 13, color: COLORS.textSecondary, marginTop: 1 },
  scheduleTide:    { fontSize: 12, color: COLORS.textMuted, marginTop: 3 },

  // Action buttons (share/download)
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 24,
  },
  actionBtn: {
    flex: 1,
    backgroundColor: COLORS.navyLight,
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  actionBtnIcon: {
    fontSize: 16,
    color: COLORS.seafoam,
  },
  actionBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.seafoam,
    fontFamily: MONO,
    letterSpacing: 1.5,
  },

  // Chartplotter GPX export
  chartplotterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.navyLight,
    borderRadius: 8,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginTop: 12,
    gap: 12,
  },
  chartplotterIcon: {
    fontSize: 24,
  },
  chartplotterText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.white,
    fontFamily: MONO,
    letterSpacing: 1.5,
  },
  chartplotterSub: {
    fontSize: 11,
    color: COLORS.textMuted,
    marginTop: 2,
  },

  // Goin' Fishin' CTA
  goinFishin: {
    backgroundColor: COLORS.seafoam,
    borderRadius: 10,
    paddingVertical: 20,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginTop: 24,
  },
  goinFishinText: {
    fontSize: 17,
    fontWeight: '800',
    color: COLORS.navy,
    fontFamily: MONO,
    letterSpacing: 2,
  },
  goinFishinSub: {
    fontSize: 12,
    color: COLORS.navy,
    marginTop: 4,
    opacity: 0.7,
  },

  // Print button (web)
  printBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.navyLight,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 12,
    gap: 10,
  },
  printBtnIcon: {
    fontSize: 18,
  },
  printBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.white,
    fontFamily: MONO,
    letterSpacing: 1.5,
  },
});
